# Change these first
owner: lgimenezdev # Your GitHub organization or username, where this repository lives
repo: samsanet # The name of this repository

sites:
  - name: INTRANET
    url: https://intranet.samsa.com.ar
  - name: MP
    url: https://mp.samsa.com.ar:8889
  - name: Acceso Clientes
    url: https://intranet.samsa.com.ar/apex/f?p=1000
  - name: INTERNET FIBE
    url: fibertel.samsa.com.ar
  - name: INTERNET GIGA
    url: gigared.samsa.com.ar
  - name: SITIO WEB
    url: https://samsa.com.ar

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.samsa.com.ar
  #baseUrl: /samsanet
  logoUrl: https://samsa.com.ar/assets/images/logosamsacompleto-1-192x67.png
  name: Estado de Servicios Informáticos
  introTitle: "**Upptime** Desde aquí podés observar el estado de los enlaces."
  introMessage: Sistema de monitoreo **tiempo real**.
  navbar:
    - title: Status
      href: /
    - title: Servicios de Agua de Misiones
      href: https://samsa.com.ar

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
