# Change these first
owner: lgimenezdev # Your GitHub organization or username, where this repository lives
repo: samsanet # The name of this repository

sites:
  - name: INTRANET
    url: https://intranet.samsa.com.ar
  - name: MP
    url: https://mp.samsa.com.ar:8889
  - name: Acceso Clientes
    url: https://intranet.samsa.com.ar/apex/f?p=1000
  - name: Acceso Contratistas
    url: https://intranet.samsa.com.ar/siga/f?p=134
  - name: INTERNET
    url: http://fibertel.samsa.com.ar/testinet/fibertel/
  - name: SITIO WEB
    url: https://samsa.com.ar

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /samsanet
  logoUrl: https://samsa.com.ar/assets/images/logosamsacompleto-1-192x67.png
  name: Estado de Servicios Informáticos
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Sistema de monitoreo **tiempo real**.
  navbar:
    - title: Status
      href: /
    - title: Servicios de Agua de Misiones
      href: https://samsa.com.ar

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
